NFLapp/urls.py
# urls.py
# urls.py en la aplicación 'nfl'
from django.urls import path
from .views import *

app_name = 'nfl'

urlpatterns = [
    path('equipos/', ListEquipos.as_view(), name='list_equipos'),
    path('equipos/<int:pk>/', DetailEquipo.as_view(), name='detail_equipo'),
    path('equipos/nuevo/', CreateEquipo.as_view(), name='create_equipo'),
    path('equipos/editar/<int:pk>/', UpdateEquipo.as_view(), name='update_equipo'),
    path('equipos/eliminar/<int:pk>/', DeleteEquipo.as_view(), name='delete_equipo'),
    path('estadios/', ListEstadios.as_view(), name='list_estadios'),
    path('estadios/<int:pk>/', DetailEstadio.as_view(), name='detail_estadio'),
    path('estadios/nuevo/', CreateEstadio.as_view(), name='create_estadio'),
    path('estadios/editar/<int:pk>/', UpdateEstadio.as_view(), name='update_estadio'),
    path('estadios/eliminar/<int:pk>/', DeleteEstadio.as_view(), name='delete_estadio'),
    path('jugadores/', ListJugadores.as_view(), name='list_jugadores'),
    path('jugadores/<int:pk>/', DetailJugador.as_view(), name='detail_jugador'),
    path('jugadores/nuevo/', CreateJugador.as_view(), name='create_jugador'),
    path('jugadores/editar/<int:pk>/', UpdateJugador.as_view(), name='update_jugador'),
    path('jugadores/eliminar/<int:pk>/', DeleteJugador.as_view(), name='delete_jugador'),
]

api/urls.py
from django.urls import path

from api import views

app_name = "api"

urlpatterns = [
    path('v2/list/grantgoal/', views.GrantGoalListAPIView.as_view(), name="api_list_grantgoal"),
    path('v2/detail/grantgoal/<int:pk>/', views.GrantGoalDetailAPIView.as_view(), name="api_detail_grantgoal"),
    path('v2/create/grantgoal/', views.GrantGoalCreateAPIView.as_view(), name="api_create_grantgoal"),

    ### URL'S CLIENT ####

    path('client/list/grantgoal/', views.ListGrantGoalClient.as_view(), name="client_list"),
    path('client/create/grantgoal/', views.CreateGrantGoalClient.as_view(), name="api_create_client")
]

home/urls.py
from django.urls import path




from home import views


app_name = "home"

urlpatterns = [
    path('', views.Index.as_view(), name="index"),
    path('login/', views.LoginView.as_view(), name="login"),
    path('logout/', views.logoutView, name="logout"),
    path('signup/', views.SignUp.as_view(), name="signup"),
    path('detail/profile/<int:pk>/', views.ProfileView.as_view(), name="profile_view"),
    path('udpate/profile/<int:pk>/', views.UpdateProfile.as_view(), name="update_profile"),
]

remedial/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
    path('core/', include("core.urls")),
    path('api/', include("api.urls")),
    path('nfl/', include("nfl.urls")),
]

templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col">
                <!-- NAV BAR -->
                <nav class="navbar navbar-expand-lg bg-body-tertiary">
                    <div class="container-fluid">
                      <a class="navbar-brand" href="{% url 'home:index' %}">
                        <img alt="logo" class="img-fluid" data-src="https://static.www.nfl.com/image/upload/v1554321393/league/nvfr7ogywskqrfaiu38m.svg" src="https://static.www.nfl.com/image/upload/v1554321393/league/nvfr7ogywskqrfaiu38m.svg">
                    </a>
                      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                      </button>
                      <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                          <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'home:index' %}">Home</a>
                          </li>
                          <li class="nav-item">
                            <a class="nav-link" href="{% url 'nfl:list_equipos' %}">NFL Teams</a>
                          </li>
                          <li class="nav-item">
                            <a class="nav-link" href="{% url 'nfl:list_estadios' %}">NFL Stadiums</a>
                          </li>
                          <li class="nav-item">
                            <a class="nav-link" href="{% url 'nfl:list_jugadores' %}">NFL Players</a>
                          </li>
                        </ul>

                        {% if request.user.is_authenticated %}
                          <a href="{% url 'home:profile_view' request.user.id %}">{{ request.user }}</a> | <a href="{% url 'home:logout' %}">Logout</a>
                        {% else %}
                          <a href="{% url 'home:login' %}">LogIn</a>
                        {% endif %}


                        <form class="d-flex" role="search">
                          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                          <button class="btn btn-outline-success" type="submit">Search</button>
                        </form>
                      </div>
                    </div>
                  </nav>
                <!-- END NAV BAR -->
            </div>
        </div>
        <div class="row">
            <div class="col-2"></div>
            <div class="col-8">
                {% block content %}
                  
                {% endblock content %}
            </div>
            <div class="col-2"></div>
        </div>
        <div class="row">
            <div class="col">
                <footer class="text-center text-white" style="background-color: #f1f1f1;">
                    <!-- Grid container -->
                    <div class="container pt-4">
                      <!-- Section: Social media -->
                      <section class="mb-4">
                        <!-- Facebook -->
                        <a
                          class="btn btn-link btn-floating btn-lg text-dark m-1"
                          href="#!"
                          role="button"
                          data-mdb-ripple-color="dark"
                          ><i class="fab fa-facebook-f"></i
                        ></a>
                  
                        <!-- Twitter -->
                        <a
                          class="btn btn-link btn-floating btn-lg text-dark m-1"
                          href="#!"
                          role="button"
                          data-mdb-ripple-color="dark"
                          ><i class="fab fa-twitter"></i
                        ></a>

                        <i class="glyphicon glyphicon-cloud"></i>

                  
                        <!-- Google -->
                        <a
                          class="btn btn-link btn-floating btn-lg text-dark m-1"
                          href="#!"
                          role="button"
                          data-mdb-ripple-color="dark"
                          ><i class="fab fa-google"></i
                        ></a>
                  
                        <!-- Instagram -->
                        <a
                          class="btn btn-link btn-floating btn-lg text-dark m-1"
                          href="#!"
                          role="button"
                          data-mdb-ripple-color="dark"
                          ><i class="fab fa-instagram"></i
                        ></a>
                  
                        <!-- Linkedin -->
                        <a
                          class="btn btn-link btn-floating btn-lg text-dark m-1"
                          href="#!"
                          role="button"
                          data-mdb-ripple-color="dark"
                          ><i class="fab fa-linkedin"></i
                        ></a>
                        <!-- Github -->
                        <a
                          class="btn btn-link btn-floating btn-lg text-dark m-1"
                          href="#!"
                          role="button"
                          data-mdb-ripple-color="dark"
                          ><i class="fab fa-github"></i
                        ></a>
                      </section>
                      <!-- Section: Social media -->
                    </div>
                    <!-- Grid container -->
                  
                    <!-- Copyright -->
                    <div class="text-center text-dark p-3" style="background-color: rgba(0, 0, 0, 0.2);">
                      © 2020 Copyright:
                      <a class="text-dark" href="https://mdbootstrap.com/">MDBootstrap.com</a>
                    </div>
                    <!-- Copyright -->
                  </footer>
            </div>
        </div>
    </div>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

templates/base/error.html
{% extends "base/base.html" %}

{% block title %}
  ERROR VIEW
{% endblock title %}

{% block content %}
    <h1>Error en login, favor de revisar las credenciales</h1>
    <a href="{% url 'home:login' %}" class="btn btn-primary">Return Login</a>
{% endblock content %}

templates/base/index.html
{% extends 'base/base.html' %}

{% block title %}IndexViews{% endblock title %}

{% block content %}
    {% if request.user.is_authenticated %}
        <div class="card">
            <div class="card-body">
                <h1 class="card-title">¡Bienvenido, {{ request.user.username }}!</h1>
                <p class="card-text">Disfruta de tu experiencia personalizada en nuestro sitio.</p>
            </div>
        </div>
    {% else %}
        <div class="card">
            <div class="card-body">
                <h1 class="card-title">¡Bienvenido a la Página Principal!</h1>
                <p class="card-text">Aquí encontrarás información interesante sobre nuestro sitio.</p>
            </div>
        </div>

        <div class="card mt-3">
            <div class="card-body">
                <h2 class="card-title">¡Inicia Sesión para una Experiencia Personalizada!</h2>
                <a href="{% url 'home:login' %}" class="btn btn-primary">Iniciar Sesión</a>
                <p class="card-text">¿No tienes una cuenta? Regístrate <a href="{% url 'home:signup' %}">aquí</a></p>
            </div>
        </div>

    {% endif %}

{% endblock content %}



 

templates/base/login.html
{% extends "base/base.html" %}

{% block title %}
  LOGIN VIEW
{% endblock title %}

{% block content %}
  <form action="" method="post" class="form">
    {% csrf_token %}
    {{ form }}
    <br><hr>
    <button type="submit" class="btn btn-primary">LogIn</button>
    <a href="{% url 'home:login' %}" class="btn btn-warning">Cancel</a>
  </form>
  <p>Si no tienes una cuenta Registrate <a href="{% url 'home:signup' %}" class="btn btn-link">Aqui</a></p>
{% endblock content %}

templates/base/profile_view.html
{% extends "base/base.html" %}

{% block title %}
  DETAIL PROFILE VIEW
{% endblock title %}

{% block content %}
<div class="accordion" id="accordionExample">
    <div class="accordion-item">
      <h2 class="accordion-header" id="headingOne">
        <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
            {{ request.user  }}
        </button>
      </h2>
      <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
        <div class="accordion-body">
          <strong>This is the Bio for {{ request.user }}.</strong><hr> <br>
           {{ profile.bio }}
        </div>
        
      </div>
    </div>
    <div class="accordion-item">
      <h2 class="accordion-header" id="headingTwo">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
          Date Data
        </button>
      </h2>
      <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
        <div class="accordion-body">
          <strong>This is the timestamp for user: {{ profile.name }}. </strong> <br>
          
          The status for the {{ profile.name }} is: {{ profile.status }}
          <br>
    
          <a href="{% url 'home:update_profile' request.user.id %}">Update Profile</a> 
        </div>
      </div>
    </div>
  </div>
  
{% endblock content %}

templates/base/signup.html
{% extends "base/base.html" %}

{% block title %}
  SIGNUP VIEW
{% endblock title %}

{% block content %}
    <form action="" method="post" class="form">
        {% csrf_token %}
            {{ form }}
            <button type="submit" class="btn btn-outline-success form-control">SignUp</button>
            <a href="{% url 'home:login' %}" class="btn btn-outline-warning form-control">Cancel</a>
    </form>
{% endblock content %}

templates/base/update_profile.html
{% extends "base/base.html" %}

{% block title %}
  UPDATE PROFILE VIEW
{% endblock title %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
            {{ form }}
            <button type="submit" class="btn btn-outline-primary">Update Profile</button>
            <!-- <a href="{% url 'home:index' %}" class="btn btn-outline-warning">Cancel</a> -->
            <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-outline-warning">Cancel</a>
    </form>
{% endblock content %}