NFLapp/urls.py
# urls.py
# urls.py en la aplicación 'nfl'
from django.urls import path
from .views import *

app_name = 'nfl'

urlpatterns = [
    path('equipos/', ListEquipos.as_view(), name='list_equipos'),
    path('equipos/<int:pk>/', DetailEquipo.as_view(), name='detail_equipo'),
    path('equipos/nuevo/', CreateEquipo.as_view(), name='create_equipo'),
    path('equipos/editar/<int:pk>/', UpdateEquipo.as_view(), name='update_equipo'),
    path('equipos/eliminar/<int:pk>/', DeleteEquipo.as_view(), name='delete_equipo'),
    path('estadios/', ListEstadios.as_view(), name='list_estadios'),
    path('estadios/<int:pk>/', DetailEstadio.as_view(), name='detail_estadio'),
    path('estadios/nuevo/', CreateEstadio.as_view(), name='create_estadio'),
    path('estadios/editar/<int:pk>/', UpdateEstadio.as_view(), name='update_estadio'),
    path('estadios/eliminar/<int:pk>/', DeleteEstadio.as_view(), name='delete_estadio'),
    path('jugadores/', ListJugadores.as_view(), name='list_jugadores'),
    path('jugadores/<int:pk>/', DetailJugador.as_view(), name='detail_jugador'),
    path('jugadores/nuevo/', CreateJugador.as_view(), name='create_jugador'),
    path('jugadores/editar/<int:pk>/', UpdateJugador.as_view(), name='update_jugador'),
    path('jugadores/eliminar/<int:pk>/', DeleteJugador.as_view(), name='delete_jugador'),
]

api/urls.py
from django.urls import path

from api import views

app_name = "api"

urlpatterns = [
    path('v2/list/grantgoal/', views.GrantGoalListAPIView.as_view(), name="api_list_grantgoal"),
    path('v2/detail/grantgoal/<int:pk>/', views.GrantGoalDetailAPIView.as_view(), name="api_detail_grantgoal"),
    path('v2/create/grantgoal/', views.GrantGoalCreateAPIView.as_view(), name="api_create_grantgoal"),

    ### URL'S CLIENT ####

    path('client/list/grantgoal/', views.ListGrantGoalClient.as_view(), name="client_list"),
    path('client/create/grantgoal/', views.CreateGrantGoalClient.as_view(), name="api_create_client")
]

remedial/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
    path('core/', include("core.urls")),
    path('api/', include("api.urls")),
    path('nfl/', include("nfl.urls")),
]

templates/NFL_cruds/players/create_jugador.html
{% extends "base/base.html" %}

{% block title %}
  CREATE PLAYER VIEW
{% endblock title %}

{% block content %}
    <form action="" method="post" class="form">
        {% csrf_token %}
            {{ form }}
            <button type="submit" class="btn btn-outline-success form-control">Create</button>
            <a href="{% url 'nfl:list_jugadores' %}" class="btn btn-outline-warning form-control">Cancel</a>
    </form>
{% endblock content %}

templates/NFL_cruds/players/delete_jugador.html
{% extends "base/base.html" %}

{% block title %}
  DELETE PLAYER VIEW
{% endblock title %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
            <h2>¿Realmente deseas eliminar el jugador: {{ jugador.nombre }}?</h2>
        <a href="{% url 'nfl:list_jugadores' %}" class="btn btn-warning">Cancel</a>
        <button type="submit" class="btn btn-danger">Delete Player</button>
    </form>
{% endblock content %}

templates/NFL_cruds/players/detail_jugador.html
{% extends "base/base.html" %}

{% block title %}
  DETAIL PLAYER VIEW
{% endblock title %}

{% block content %}
<div class="accordion" id="accordionExample">
    <div class="accordion-item">
      <h2 class="accordion-header" id="headingOne">
        <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
            {{ jugador.nombre }}
        </button>
      </h2>
      <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
        <div class="accordion-body">
          <strong>Este es el jugador {{ jugador.nombre }}.</strong> {{ jugador.descripcion }}
        </div>
        
      </div>
    </div>
    <div class="accordion-item">
      <h2 class="accordion-header" id="headingTwo">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
          Información Adicional
        </button>
      </h2>
      <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
        <div class="accordion-body">
          <strong>La posición del jugador es {{ jugador.posicion }}.</strong> Pertenece al equipo {{ jugador.equipo.nombre }}.
          <br>
          <br>
          <a href="{% url 'nfl:list_jugadores' %}">Volver a la lista de jugadores</a> 
        </div>
      </div>
    </div>
  </div>
  
{% endblock content %}

templates/NFL_cruds/players/list_jugadores.html
{% extends "base/base.html" %}

{% block title %}
  LIST JUGADORES VIEW
{% endblock title %}

{% block content %}
    <table class="table">
        <thead>
            <th>ID</th>
            <th>Nombre</th>
            <th>Posición</th>
            <th>Equipo</th>
            <th></th>
            <th>ACTIONS</th>
            <th></th>
        </thead>
        <tbody>
            {% for jugador in object_list %}
                <tr>
                    <td>{{ jugador.id }}</td>
                    <td>{{ jugador.nombre }}</td>
                    <td>{{ jugador.posicion }}</td>
                    <td>{{ jugador.equipo.nombre }}</td>
                    <td><a href="{% url 'nfl:detail_jugador' jugador.id %}" class="btn btn-outline-info">Detail</a></td>
                    <td><a href="{% url 'nfl:update_jugador' jugador.id %}" class="btn btn-outline-warning">Update</a></td>
                    <td><a href="{% url 'nfl:delete_jugador' jugador.id %}" class="btn btn-outline-danger">Delete</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <a href="{% url 'nfl:create_jugador' %}" class="btn btn-outline-success">Agregar Jugador</a>
{% endblock content %}

templates/NFL_cruds/players/update_jugador.html
{% extends "base/base.html" %}

{% block title %}
  UPDATE PLAYER VIEW
{% endblock title %}

{% block content %}
    <form action="" method="post" class="form">
        {% csrf_token %}
            {{ form }}
            <button type="submit" class="btn btn-outline-primary form-control">Update</button>
            <a href="{% url 'nfl:list_jugadores' %}" class="btn btn-outline-warning form-control">Cancel</a>
    </form>
{% endblock content %}